### ISSUE TITLE
Got "fatal: Not a git repository (or any of the parent directories): .git" when compiling libinvm-cli

### ISSUE THREAD

**Issue by yide1728** [01org/libinvm-cli#3]
#wget https://github.com/01org/libinvm-cli/archive/v1.0.0.1096.tar.gz#/libinvm-cli-1.0.0.1096.tar.gz 
#tar xvf v1.0.0.1096.tar.gz
#cd libinvm-cli-1.0.0.1096
#make
fatal: Not a git repository (or any of the parent directories): .git
mkdir -p output/build/linux/debug
make -C src framework SKIP_UNITTESTS=1
fatal: Not a git repository (or any of the parent directories): .git
make[1]: Entering directory `/root/rpmbuild/SOURCES/tmp/libinvm-cli-1.0.0.1096/src'
make -C framework all
fatal: Not a git repository (or any of the parent directories): .git
make[2]: Entering directory `/root/rpmbuild/SOURCES/tmp/libinvm-cli-1.0.0.1096/src/framework'
mkdir -p ../../output/obj/linux/debug/framework
g++ -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999 -D__ADD_MANUFACTURING__=1 -D__INTEL_I18N__ -D__LINUX__ -DPOCO_STATIC   -I../../external/intel_i18n/include -c osAdapter.cpp -o ../../output/obj/linux/debug/framework/osAdapter.o
g++ -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999 -D__ADD_MANUFACTURING__=1 -D__INTEL_I18N__ -D__LINUX__ -DPOCO_STATIC   -I../../external/intel_i18n/include -c ResultBase.cpp -o ../../output/obj/linux/debug/framework/ResultBase.o
g++ -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999 -D__ADD_MANUFACTURING__=1 -D__INTEL_I18N__ -D__LINUX__ -DPOCO_STATIC   -I../../external/intel_i18n/include -c SimpleListResult.cpp -o ../../output/obj/linux/debug/framework/SimpleListResult.o
g++ -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999 -D__ADD_MANUFACTURING__=1 -D__INTEL_I18N__ -D__LINUX__ -DPOCO_STATIC   -I../../external/intel_i18n/include -c SyntaxErrorUnexpectedValueResult.cpp -o ../../output/obj/linux/debug/framework/SyntaxErrorUnexpectedValueResult.o
g++ -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999 -D__ADD_MANUFACTURING__=1 -D__INTEL_I18N__ -D__LINUX__ -DPOCO_STATIC   -I../../external/intel_i18n/include -c HelpResult.cpp -o ../../output/obj/linux/debug/framework/HelpResult.o
g++ -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999 -D__ADD_MANUFACTURING__=1 -D__INTEL_I18N__ -D__LINUX__ -DPOCO_STATIC   -I../../external/intel_i18n/include -c PropertyListResult.cpp -o ../../output/obj/linux/debug/framework/PropertyListResult.o
g++ -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999 -D__ADD_MANUFACTURING__=1 -D__INTEL_I18N__ -D__LINUX__ -DPOCO_STATIC   -I../../external/intel_i18n/include -c SyntaxErrorResult.cpp -o ../../output/obj/linux/debug/framework/SyntaxErrorResult.o
g++ -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999 -D__ADD_MANUFACTURING__=1 -D__INTEL_I18N__ -D__LINUX__ -DPOCO_STATIC   -I../../external/intel_i18n/include -c FeatureBase.cpp -o ../../output/obj/linux/debug/framework/FeatureBase.o
g++ -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999 -D__ADD_MANUFACTURING__=1 -D__INTEL_I18N__ -D__LINUX__ -DPOCO_STATIC   -I../../external/intel_i18n/include -c SyntaxErrorMissingValueResult.cpp -o ../../output/obj/linux/debug/framework/SyntaxErrorMissingValueResult.o
g++ -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999 -D__ADD_MANUFACTURING__=1 -D__INTEL_I18N__ -D__LINUX__ -DPOCO_STATIC   -I../../external/intel_i18n/include -c Parser.cpp -o ../../output/obj/linux/debug/framework/Parser.o
g++ -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999 -D__ADD_MANUFACTURING__=1 -D__INTEL_I18N__ -D__LINUX__ -DPOCO_STATIC   -I../../external/intel_i18n/include -c NoInputErrorResult.cpp -o ../../output/obj/linux/debug/framework/NoInputErrorResult.o
g++ -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999 -D__ADD_MANUFACTURING__=1 -D__INTEL_I18N__ -D__LINUX__ -DPOCO_STATIC   -I../../external/intel_i18n/include -c ObjectListResult.cpp -o ../../output/obj/linux/debug/framework/ObjectListResult.o
g++ -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999 -D__ADD_MANUFACTURING__=1 -D__INTEL_I18N__ -D__LINUX__ -DPOCO_STATIC   -I../../external/intel_i18n/include -c SyntaxErrorBadValueResult.cpp -o ../../output/obj/linux/debug/framework/SyntaxErrorBadValueResult.o
g++ -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999 -D__ADD_MANUFACTURING__=1 -D__INTEL_I18N__ -D__LINUX__ -DPOCO_STATIC   -I../../external/intel_i18n/include -c ParseErrorResult.cpp -o ../../output/obj/linux/debug/framework/ParseErrorResult.o
g++ -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999 -D__ADD_MANUFACTURING__=1 -D__INTEL_I18N__ -D__LINUX__ -DPOCO_STATIC   -I../../external/intel_i18n/include -c HelpFeature.cpp -o ../../output/obj/linux/debug/framework/HelpFeature.o
g++ -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999 -D__ADD_MANUFACTURING__=1 -D__INTEL_I18N__ -D__LINUX__ -DPOCO_STATIC   -I../../external/intel_i18n/include -c NotImplementedErrorResult.cpp -o ../../output/obj/linux/debug/framework/NotImplementedErrorResult.o
g++ -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999 -D__ADD_MANUFACTURING__=1 -D__INTEL_I18N__ -D__LINUX__ -DPOCO_STATIC   -I../../external/intel_i18n/include -c Lexer.cpp -o ../../output/obj/linux/debug/framework/Lexer.o
g++ -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999 -D__ADD_MANUFACTURING__=1 -D__INTEL_I18N__ -D__LINUX__ -DPOCO_STATIC   -I../../external/intel_i18n/include -c CommandFilter.cpp -o ../../output/obj/linux/debug/framework/CommandFilter.o
g++ -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999 -D__ADD_MANUFACTURING__=1 -D__INTEL_I18N__ -D__LINUX__ -DPOCO_STATIC   -I../../external/intel_i18n/include -c SimpleResult.cpp -o ../../output/obj/linux/debug/framework/SimpleResult.o
g++ -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999 -D__ADD_MANUFACTURING__=1 -D__INTEL_I18N__ -D__LINUX__ -DPOCO_STATIC   -I../../external/intel_i18n/include -c Logger.cpp -o ../../output/obj/linux/debug/framework/Logger.o
g++ -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999 -D__ADD_MANUFACTURING__=1 -D__INTEL_I18N__ -D__LINUX__ -DPOCO_STATIC   -I../../external/intel_i18n/include -c DuplicateTokenErrorResult.cpp -o ../../output/obj/linux/debug/framework/DuplicateTokenErrorResult.o
g++ -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999 -D__ADD_MANUFACTURING__=1 -D__INTEL_I18N__ -D__LINUX__ -DPOCO_STATIC   -I../../external/intel_i18n/include -c CliFrameworkTypes.cpp -o ../../output/obj/linux/debug/framework/CliFrameworkTypes.o
g++ -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999 -D__ADD_MANUFACTURING__=1 -D__INTEL_I18N__ -D__LINUX__ -DPOCO_STATIC   -I../../external/intel_i18n/include -c ErrorResult.cpp -o ../../output/obj/linux/debug/framework/ErrorResult.o
g++ -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999 -D__ADD_MANUFACTURING__=1 -D__INTEL_I18N__ -D__LINUX__ -DPOCO_STATIC   -I../../external/intel_i18n/include -c Trace.cpp -o ../../output/obj/linux/debug/framework/Trace.o
g++ -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999 -D__ADD_MANUFACTURING__=1 -D__INTEL_I18N__ -D__LINUX__ -DPOCO_STATIC   -I../../external/intel_i18n/include -c Framework.cpp -o ../../output/obj/linux/debug/framework/Framework.o
g++ -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999 -D__ADD_MANUFACTURING__=1 -D__INTEL_I18N__ -D__LINUX__ -DPOCO_STATIC   -I../../external/intel_i18n/include -c CommandSpec.cpp -o ../../output/obj/linux/debug/framework/CommandSpec.o
g++ -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999 -D__ADD_MANUFACTURING__=1 -D__INTEL_I18N__ -D__LINUX__ -DPOCO_STATIC   -I../../external/intel_i18n/include -c CommandVerify.cpp -o ../../output/obj/linux/debug/framework/CommandVerify.o
mkdir -p ../../output/build/linux/debug/include/libinvm-cli
cp -rav --parents CliFrameworkTypes.h CommandSpec.h DuplicateTokenErrorResult.h ErrorResult.h FeatureBase.h FeatureRef.h Framework.h HelpFeature.h Logger.h NoInputErrorResult.h NotImplementedErrorResult.h ObjectListResult.h Parser.h PropertyListResult.h ResultBase.h SimpleListResult.h SimpleResult.h SyntaxErrorBadValueResult.h SyntaxErrorMissingValueResult.h SyntaxErrorUnexpectedValueResult.h SyntaxErrorResult.h Trace.h ../../output/build/linux/debug/include/libinvm-cli
‘CliFrameworkTypes.h’ -> ‘../../output/build/linux/debug/include/libinvm-cli/CliFrameworkTypes.h’
‘CommandSpec.h’ -> ‘../../output/build/linux/debug/include/libinvm-cli/CommandSpec.h’
‘DuplicateTokenErrorResult.h’ -> ‘../../output/build/linux/debug/include/libinvm-cli/DuplicateTokenErrorResult.h’
‘ErrorResult.h’ -> ‘../../output/build/linux/debug/include/libinvm-cli/ErrorResult.h’
‘FeatureBase.h’ -> ‘../../output/build/linux/debug/include/libinvm-cli/FeatureBase.h’
‘FeatureRef.h’ -> ‘../../output/build/linux/debug/include/libinvm-cli/FeatureRef.h’
‘Framework.h’ -> ‘../../output/build/linux/debug/include/libinvm-cli/Framework.h’
‘HelpFeature.h’ -> ‘../../output/build/linux/debug/include/libinvm-cli/HelpFeature.h’
‘Logger.h’ -> ‘../../output/build/linux/debug/include/libinvm-cli/Logger.h’
‘NoInputErrorResult.h’ -> ‘../../output/build/linux/debug/include/libinvm-cli/NoInputErrorResult.h’
‘NotImplementedErrorResult.h’ -> ‘../../output/build/linux/debug/include/libinvm-cli/NotImplementedErrorResult.h’
‘ObjectListResult.h’ -> ‘../../output/build/linux/debug/include/libinvm-cli/ObjectListResult.h’
‘Parser.h’ -> ‘../../output/build/linux/debug/include/libinvm-cli/Parser.h’
‘PropertyListResult.h’ -> ‘../../output/build/linux/debug/include/libinvm-cli/PropertyListResult.h’
‘ResultBase.h’ -> ‘../../output/build/linux/debug/include/libinvm-cli/ResultBase.h’
‘SimpleListResult.h’ -> ‘../../output/build/linux/debug/include/libinvm-cli/SimpleListResult.h’
‘SimpleResult.h’ -> ‘../../output/build/linux/debug/include/libinvm-cli/SimpleResult.h’
‘SyntaxErrorBadValueResult.h’ -> ‘../../output/build/linux/debug/include/libinvm-cli/SyntaxErrorBadValueResult.h’
‘SyntaxErrorMissingValueResult.h’ -> ‘../../output/build/linux/debug/include/libinvm-cli/SyntaxErrorMissingValueResult.h’
‘SyntaxErrorUnexpectedValueResult.h’ -> ‘../../output/build/linux/debug/include/libinvm-cli/SyntaxErrorUnexpectedValueResult.h’
‘SyntaxErrorResult.h’ -> ‘../../output/build/linux/debug/include/libinvm-cli/SyntaxErrorResult.h’
‘Trace.h’ -> ‘../../output/build/linux/debug/include/libinvm-cli/Trace.h’
g++ -Wall -Werror -Wfatal-errors -fstack-protector-all -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=500  -fPIC -m64 -O -ggdb  -MMD -D__VERSION_MAJOR__=99 -D__VERSION_MINOR__=99 -D__VERSION_HOTFIX__=99 -D__VERSION_BUILDNUM__=9999 -D__VERSION_NUMBER__=99.99.99.9999 -D__ADD_MANUFACTURING__=1 -D__INTEL_I18N__ -D__LINUX__ -DPOCO_STATIC   -shared ../../output/obj/linux/debug/framework/osAdapter.o ../../output/obj/linux/debug/framework/ResultBase.o ../../output/obj/linux/debug/framework/SimpleListResult.o ../../output/obj/linux/debug/framework/SyntaxErrorUnexpectedValueResult.o ../../output/obj/linux/debug/framework/HelpResult.o ../../output/obj/linux/debug/framework/PropertyListResult.o ../../output/obj/linux/debug/framework/SyntaxErrorResult.o ../../output/obj/linux/debug/framework/FeatureBase.o ../../output/obj/linux/debug/framework/SyntaxErrorMissingValueResult.o ../../output/obj/linux/debug/framework/Parser.o ../../output/obj/linux/debug/framework/NoInputErrorResult.o ../../output/obj/linux/debug/framework/ObjectListResult.o ../../output/obj/linux/debug/framework/SyntaxErrorBadValueResult.o ../../output/obj/linux/debug/framework/ParseErrorResult.o ../../output/obj/linux/debug/framework/HelpFeature.o ../../output/obj/linux/debug/framework/NotImplementedErrorResult.o ../../output/obj/linux/debug/framework/Lexer.o ../../output/obj/linux/debug/framework/CommandFilter.o ../../output/obj/linux/debug/framework/SimpleResult.o ../../output/obj/linux/debug/framework/Logger.o ../../output/obj/linux/debug/framework/DuplicateTokenErrorResult.o ../../output/obj/linux/debug/framework/CliFrameworkTypes.o ../../output/obj/linux/debug/framework/ErrorResult.o ../../output/obj/linux/debug/framework/Trace.o ../../output/obj/linux/debug/framework/Framework.o ../../output/obj/linux/debug/framework/CommandSpec.o ../../output/obj/linux/debug/framework/CommandVerify.o -L../../output/build/linux/debug -ldl -linvm-i18n -Wl,--as-needed,-soname,libinvm-cli.so.99 -o ../../output/build/linux/debug/libinvm-cli.so.99.99.0
cd ../../output/build/linux/debug; rm -f libinvm-cli.so.99; ln -s libinvm-cli.so.99.99.0 libinvm-cli.so.99
cd ../../output/build/linux/debug; rm -f libinvm-cli.so; ln -s libinvm-cli.so.99.99.0 libinvm-cli.so
make[2]: Leaving directory `/root/rpmbuild/SOURCES/tmp/libinvm-cli-1.0.0.1096/src/framework'
make[1]: Leaving directory `/root/rpmbuild/SOURCES/tmp/libinvm-cli-1.0.0.1096/src'
make i18n 
fatal: Not a git repository (or any of the parent directories): .git
make[1]: Entering directory `/root/rpmbuild/SOURCES/tmp/libinvm-cli-1.0.0.1096'
make -C src i18n SKIP_UNITTESTS=1
fatal: Not a git repository (or any of the parent directories): .git
make[2]: Entering directory `/root/rpmbuild/SOURCES/tmp/libinvm-cli-1.0.0.1096/src'
make -C framework i18n
fatal: Not a git repository (or any of the parent directories): .git
make[3]: Entering directory `/root/rpmbuild/SOURCES/tmp/libinvm-cli-1.0.0.1096/src/framework'
touch ../../output/build/linux/debug/en-US.pot; xgettext --keyword=N_TR --keyword=TR -j -o ../../output/build/linux/debug/en-US.pot *.cpp
touch ../../output/build/linux/debug/en-US.pot; xgettext --keyword=N_TR --keyword=TR -j -o ../../output/build/linux/debug/en-US.pot *.h	
make[3]: Leaving directory `/root/rpmbuild/SOURCES/tmp/libinvm-cli-1.0.0.1096/src/framework'
make[2]: Leaving directory `/root/rpmbuild/SOURCES/tmp/libinvm-cli-1.0.0.1096/src'
# an example translation file
mkdir -p /root/rpmbuild/SOURCES/tmp/libinvm-cli-1.0.0.1096/output/build/linux/debug/lang # where translation must go
msgmerge ./lang/en_US.po ./output/build/linux/debug/en-US.pot -o /root/rpmbuild/SOURCES/tmp/libinvm-cli-1.0.0.1096/output/build/linux/debug/lang/en-US.po
............................. done.
# Any new translations should happen before the .mo file is created
msgfmt /root/rpmbuild/SOURCES/tmp/libinvm-cli-1.0.0.1096/output/build/linux/debug/lang/en-US.po -o /root/rpmbuild/SOURCES/tmp/libinvm-cli-1.0.0.1096/output/build/linux/debug/lang/en-US.mo
make[1]: Leaving directory `/root/rpmbuild/SOURCES/tmp/libinvm-cli-1.0.0.1096'

**Comment by nkothapa** [comment]
Fixed it in the latest release, Thanks for the report!
